### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by naher94** [naher94/rehanbutt.com#206]
https://kyledecker.me/about

![Dark Mode Toggle Web 2019-07-14 14_55_57](https://user-images.githubusercontent.com/7800629/61188040-870a5180-a647-11e9-91aa-26552bcf8ae5.gif)

**Comment by naher94** [comment]
https://tombrow.com/dark-mode-website-css

**Comment by naher94** [comment]
how to make the images not have weird background borders for everything and make the contrast fix irrelevant

**Comment by Dorson** [comment]
The `@media (prefers-color-scheme: dark)` rule has one disadvantage that the user can not remove it fast enough during the sunny moments, or to have zero custom color choices. It's a great CSS rule for mobile users, if the colors are selected well. Dark gray works for sunny environments too, while pure black is more difficult.

Recently, I coded the Dark Mode switch in CSS and basic Java Script.

In my version of the dark mode, we can have multiple color themes in one CSS file. Then set or remember color settings with one short JS function without logins.

**Try it** on the GitHub demo page :

https://dorson.github.io/CSS-Dark-Mode-and-color-switch/

Feel free to fork, copy, adopt, etc..

Have fun ! :+1:

**Comment by naher94** [comment]
https://francoisbest.com/posts/2020/dark-mode-for-excalidraw

**Comment by naher94** [comment]
### Check Image Backgrounds
### Update Colors on Year in Review Pages

**Comment by naher94** [comment]
`filter` on `img` is a nice touch for ease on the eyes

https://developer.mozilla.org/en-US/docs/Web/CSS/filter

**Comment by Dorson** [comment]
> `filter` on `img` is a nice touch for ease on the eyes
> 
> https://developer.mozilla.org/en-US/docs/Web/CSS/filter

There are screen modes for that on mobile devices. Mobile devices are solving that to some degree.

The Well defined dark mode colors are an asset, if the users are visiting the site or app mostly at night or for a very long time like on YTube.

**Comment by naher94** [comment]
migrate `@media (prefers-color-scheme: dark)` to a color theme rather then per element

**Comment by naher94** [comment]
https://www.sitepoint.com/dealing-color-schemes-sass/

https://web.dev/prefers-color-scheme/

**Comment by naher94** [comment]
https://codyhouse.co/blog/post/css-custom-properties-vs-sass-variables#color-themes
https://codepen.io/jakealbaugh/post/css4-variables-and-sass

https://codepen.io/naher94/pen/poNrYPN?editors=1100
