### ISSUE TITLE
‼️Not an Issue‼️

### ISSUE THREAD

**Issue by UmairJibran** [naher94/rehanbutt.com#684]
Just wanted to say, Awesome portfolio!!! 🎉

Loved that "Years in review" section the most

**Comment by naher94** [comment]
Thanks @UmairJibran !
Out of curiosity, how did you come across my site?

**Comment by UmairJibran** [comment]
Found you here on the my home page of github, yeah I use github as a social media :P

<img width="391" alt="Screenshot 2024-02-26 at 10 59 48 AM" src="https://github.com/naher94/rehanbutt.com/assets/43789374/434fe388-9c9a-45f5-bfd7-f5269d918261">

**Comment by naher94** [comment]
Oh very cool! Thanks for sharing
