### ISSUE TITLE
Jank Text on /thesis

### ISSUE THREAD

**Issue by lukehottinger** [naher94/rehanbutt.com#79]
<img width="1265" alt="screen shot 2017-01-26 at 10 20 43" src="https://cloud.githubusercontent.com/assets/13633946/22336722/2ce5541c-e3b1-11e6-8db1-8aab3f290ec2.png">

😢

**Comment by naher94** [comment]
@lukehottinger Thanks, need to expand the text in Ai

**Comment by lukehottinger** [comment]
👍

**Comment by naher94** [comment]
added to refactor branch, need to verify with other machines

**Comment by naher94** [comment]
Verified on Other machines
